### ISSUE TITLE
How do I uninstall?

### ISSUE THREAD

**Issue by In7GDS** [davidjcralph/AudacityDiscordRPC#1]
I tried uninstalling the plugin but I can't. The only solution I've found so far is to _run Audacity before Discord_ but I have to do it every time. Is there a way to uninstall the plugin?

**Comment by davidcralph** [comment]
This is not a plugin for Audacity but a separate program. Are you confusing it with something else?

**Comment by In7GDS** [comment]
I mean, how do I remove it?

**Comment by davidcralph** [comment]
Remove the folder

**Comment by In7GDS** [comment]
Okay thanks!
